// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifxhfhyvzntkenwklcdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmeGhmaHl2em50a2Vud2tsY2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTg2NzUsImV4cCI6MjA2OTA5NDY3NX0.0gfFFXrNKXSwtzM8aAuu2cut7o32j4BY8qNbPd32xak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});